cmd/sstoresload-generator/main.go
At least in `sstoresload-generator`, when the user didn't set the default path, `location` would end up being empty, and the test folder creation would be skipped. This PR initializes the location with the default location, so that this problem doesn't occur.
=> Ensure that /tmp is the default location value

common/utils.go, fuzzing/copypasta.go, fuzzing/gen_sttransaction.go, fuzzing/statetest_maker.go
We export `gst.SetTx()` but the transaction type itself is not exported which makes handling a pain
=> fuzzing: export StTransaction

common/utils.go
I wanted to add a test-mode where we only compare staterooots, and not parse outputs. When doing so, I noticed how complex the whole thing was. This is an attempt to break the test execution up a bit, and make it more modular, so it can be more easily extended to support e..g. other testmodes and/or batched executions. 
WIP
cc @MariusVanDerWijden
=> common/utils: refactor test execution

evms/besu.go, evms/geth.go, evms/parity.go
Parity updated some stuff, can now output everything in the same output chan. Fixed a flaw due to too small max buffer size on golang tokenizer.
=> evms: various fixes

cmd/traceview/main.go, ui/viewmanager.go
Currently when I open a trace in `traceview` using my standard zoom level in my terminal, it looks like this:
I modified the UI to use a flexbox instead so that it adapts to different screen sizes better.
I also found that there wasn't a good configuration that allowed me to both see 32 byte values on the stack and reasonable amount of memory, so I added a toggle (`m` key) to change the flex direction on the lower half from columns to rows.
=> Handle small displays better with single trace view

evms/besubatcher.go
Makes besu's batched evm threadsafe. Calls to the EVM are serialized
=> evms: serialize calls to besu evm

cmd/traceview/main.go, traces/reader.go, ui/viewmanager.go
Verkle trees (and other EIPs) introduce the concept of code chunking. I found it useful to add a column to display which chunk a program counter belongs to.
There are some things missing to this PR, which I'm opening to collect feedback:
This PR is therefore ready for review/merge.
=> add a "code chunk" column to the trace view

cmd/traceview/main.go
The `flag` package provides a "variable" version of each of its typed-parameter functions: it takes a pointer to the global variable instead of returning a local variable. Because @holiman added a global variable during his refactoring, might as well save some code redundancy by using the `*Var` version.
=> refactor: setting of the Chunksize global variable

go.mod
the use of binary.BigEndian.AppendUint16 was added in go version 1.19
=> bump version

evms/besu.go, evms/erigon.go, evms/geth.go, evms/nethermind.go, evms/nimbus.go
Should improve stuff: make the initial buffer smaller, but make the max size larger.
=> evms: make scanner buffer handle up to 32 MB output

cmd/generic-fuzzer/main.go, cmd/generic-generator/main.go, cmd/minimizer/main.go, cmd/runtest/main.go, common/utils.go
runtest will use the better parallelism if `--parallel` is provided
=> cmd/runtest: common: use more parallelism in fuzzer

common/utils.go, evms/geth.go, evms/gethbatcher.go
Engine for https://github.com/ethereum/go-ethereum/pull/27318
=> evms: implement gethbatch

.golangci.yml, cmd/generic-fuzzer/main.go, cmd/generic-generator/main.go, common/utils.go, evms/besu.go, evms/besubatcher.go, evms/erigon.go, evms/evms.go, evms/geth.go, evms/gethbatcher.go, evms/nethermind.go, evms/nethermindbatcher.go, evms/nimbus.go, evms/vmstats.go, utils/wma.go
This change makes things quite a bit faster, by making per-thread local instances
of the batched evms.
This means that each test executor can have it's local instance of the vm-batcher and thus
there is no locking contention around running statetest.
This PR also uses bufio writers, and a scanner-buffers from a `sync.Pool`. 
This commit also makes the sliding average concurrency-safe.
=> General speedups, show execution speed metrics

cmd/checkslow/main.go, common/utils.go, evms/besu.go, evms/erigon.go, evms/geth.go, evms/marshalling.go, evms/marshalling_test.go, evms/nethermind.go, evms/nimbus.go, evms/utils.go
Currently, all evms output is parsed, into `StructLog` items. Those are then lightly cleansed, and then marshalled into json again, and written to output files. 
In the next phase, those output files are then compared. This comparison is done line by line, and does not parse json, just compares the raw bytes. 
This PR changes the output / comparison phase. First of all, the 'standard' json marshaller is discarded, and instead a custom-made marshaller is used. This has three benefits
- It is much faster
- The custom marshaller removes the need for removing content from the log objects in a pre-step, since we can just omit emitting things we're not concerned about, 
- It only prints the top six stack items, making the output more condensed and less intensive to write and read. 
Example …
=> fuzzing: faster marshalling and comparison-phase due to less IO

common/utils.go, evms/besubatcher.go, evms/erigonbatcher.go, evms/gethbatcher.go, evms/nethermind.go, evms/nethermindbatcher.go
Also make use of atomic types, and use io.Discard
=> evms: nethermind - utilize multiple batcher instances

docker/Dockerfile
This is an attempt to bundle the fuzzing-components into one big dockerfile:
Can be run via 
```
docker run -it holiman/omnifuzz
```
=> Dockerfile for fuzzing 7 clients

cmd/runtest/main.go, cmd/testvm/main.go, cmd/testvm/readme.md, common/utils.go, evms/besu.go, evms/erigon.go, evms/evmone.go, evms/geth.go, evms/nethermind.go, evms/nimbus.go, evms/revm.go, evms/vmstats.go
This PR implements https://github.com/holiman/goevmlab/issues/120. This creates a huge speed-boost in the case where many clients are used. 
Previously, the general flow of execution was
- Generate a test
- Spin up `n` clients to execute it, 
- Wait for all to complete
- Compare the outputs
- Repeat
That is, every test is executed by `n` clients, and the slowest one sets the pace. With this PR, we instead do 
- Generate a test
- Wait until we have two clients ready, task them to execute it, 
- Whenever a client is done, handle it's output, put into ready-queue
- Repeat
That is, every test is executed by `2` clients, the first two clients that are available. Whenever a client becomes available, it is tasked with a new test shortly. 
So instead of the slowest client setting the pace, each …
=> Faster execution of fuzzing-pipeline

cmd/checkslow/main.go, cmd/generic-fuzzer/main.go, cmd/runtest/main.go, common/utils.go, docker/Dockerfile, docker/readme_docker.md, evms/evmone.go, evms/geth.go, evms/nethermind.go, evms/nethermindbatcher.go
Closes https://github.com/holiman/goevmlab/issues/132 
- Faster `evmone` speedtest (no tracing)
- Faster `nethtest/nethbatch` speedtest (no tracing)
- Faster `geth/gethbatch` speedtest (no tracing) -- requires https://github.com/ethereum/go-ethereum/pull/29290
=> faster 'checkslow' on evmone, nethbatch and gethbatch

evms/besu.go, evms/eels.go, evms/erigon.go, evms/evmone.go, evms/geth.go, evms/nethermind.go, evms/nimbus.go, evms/revm.go
This fixes a 'hang' in revme due to json parser not fully consuming all output. 
This seems to be the root cause behind https://github.com/holiman/goevmlab/issues/160 , where certain outputs would cause the runner not to finihs. 
Example testcase that hangs (e.g. tested via `runtest`) on revme without this PR: 
```
{
"00186451-mixed-10": {
"env": {
"currentCoinbase": "b94f5374fce5edbc8e2a8697c15331677e6ebf0b",
"currentDifficulty": "0x200000",
"currentRandom": "0x0000000000000000000000000000000000000000000000000000000000200000",
"currentGasLimit": "0x26e1f476fe1e22",
"currentNumber": "0x1",
"currentTimestamp": "0x3e8",
"previousHash": "0x044852b2a670ade5407e78fb2863c51de9fcb96542a07186fe3aeda6bb8a116d",
"currentBaseFee": "0x10"
},
"pre": {
"0x00000000000000000000000000000000000000f1": { …
```
=> evms: ensure to drain proc output-pipe before invoking wait. 

evms/besu.go, evms/gen_oplog.go, evms/geth.go, evms/marshalling.go, evms/oplog.go, evms/utils.go, ops/forks.go, ops/operations.go, ops/operations_test.go, traces/reader.go, ui/viewmanager.go
Adds EOF changes that don't depend on Geth EOF support or the Osaka activation.
* opcodes for EOF
* better immediate handling for opcodes
* EIP-7756 flexibility on opcode and gas
* EIP-7756 fields (section and functionDepth)
=> Non-osaka EOF changes

docker/Dockerfile
The EELS Prague implementation isn't merged into execution-specs master yet.
=> use eels forks/prague branch

docker/Dockerfile
Before, it was at `3.45B`: 
```
holiman/omnifuzz   latest            1ad5c6d0de75   9 hours ago     3.45GB
```
Details:
```
user@debian-work:~$ docker history  1ad5c6d0de75 
IMAGE          CREATED       CREATED BY                                      SIZE      COMMENT
1ad5c6d0de75   9 hours ago   ENTRYPOINT ["/bin/bash"]                        0B        buildkit.dockerfile.v0
<missing>      9 hours ago   ENV FUZZ_CLIENTS_PLAIN=--geth=/gethvm  --net…   0B        buildkit.dockerfile.v0
<missing>      9 hours ago   ENV FUZZ_CLIENTS=--gethbatch=/gethvm  --neth…   0B        buildkit.dockerfile.v0
<missing>      9 hours ago   COPY readme_docker.md /README.md # buildkit     1.47kB    buildkit.dockerfile.v0
<missing>      9 hours ago   ENV BESU_BIN=/evmtool/bin/evmtool               0B …
```
=> Smaller docker

docker/Dockerfile
Before
```
REPOSITORY         TAG               IMAGE ID       CREATED         SIZE
holiman/omnifuzz   latest            097a31ebf296   6 minutes ago   2.65GB
```
This PR
```
REPOSITORY         TAG               IMAGE ID       CREATED             SIZE
holiman/omnifuzz   latest            b9ef0224946a   3 minutes ago       2.32GB
```
```
user@debian-work:~/workspace/goevmlab/docker$ docker history b9ef0224946a
IMAGE          CREATED          CREATED BY                                      SIZE      COMMENT
b9ef0224946a   6 minutes ago    ENTRYPOINT ["/bin/bash"]                        0B        buildkit.dockerfile.v0
<missing>      6 minutes ago    ENV FUZZ_CLIENTS_PLAIN=--geth=/gethvm  --net…   0B        buildkit.dockerfile.v0
<missing>      6 minutes ago    ENV …
```
=> dockerfile: use headless java

docker/Dockerfile, docker/Dockerfile.nimbus, docker/README.md
This PR splits away the `nimbus-eth1` evm client into a separate image, and also cleans up the rust stuff in the main container. 
The split makes it so we don't have to rebuild `nimbus-eth1` each time the 'main' is rebuilt (it takes a huge amount of time), and the latter change makes the image a lot++ smaller. 
With this PR, the size has gone from `2.65GB` to `1.66GB`
```
REPOSITORY         TAG               IMAGE ID       CREATED             SIZE
holiman/omnifuzz   latest            3a384320be60   About an hour ago   1.66GB
holiman/nimbus     latest            c9e46dc09510   About an hour ago   151MB
```
```
user@debian-work:~/workspace/goevmlab/docker$ docker history holiman/omnifuzz
IMAGE          CREATED             CREATED BY                                      SIZE      COMMENT …
```
=> docker: separate nimbus-eth1 out, remove rust after installation of eels
